### ISSUE TITLE
compile error!

### ISSUE THREAD

**Issue by crankler** [ori-drs/pronto_anymal_example#1]
hi, Marco Camurri, when I compile this package ,there have this error:

/home/roma/catkin_1/src/pronto_anymal_example/anymal_robcogen/./include/anymal_robcogen/transforms.h:4:10: fatal error: iit / rbd / TransformsBase.h: No such file or directory
  #include <iit / rbd / TransformsBase.h>

And I've find it in https://github.com/ethz-adrl/control-toolbox,
do we need to git down this package and compile again ?
Thank you!

**Comment by mcamurri** [comment]
Dear @crankler , sorry for the late reply. 

The files you are looking for are  [here](https://github.com/ori-drs/pronto/tree/master/pronto_quadruped_commons/include/pronto_quadruped_commons/rbd).

The original library is called `rbd` and it has been copied inside pronto with a different name. 
As you can see, I'm using a symlink to point to the right path, which starts with `iit`.  

This works well on my computer.

Have you cloned and compiled all the modules inside the [`pronto`](https://github.com/ori-drs/pronto) repository?

**Comment by mcamurri** [comment]
@crankler do you need further assistance on this issue?

**Comment by crankler** [comment]
It's happy to receive your help, @mcamurri.
At now I have compiled completely，thank you for your advice.
We try to fuse pronto and mit open source  package, LOAM to imporve the accuracy of state estimation, but it's confused to adjust the covariance, can you show me a few reference material? 
By the way, our team notice there have 3 paper which related with factor graph, especially the last one and dataset.  We all think your group has done a great job. Can this VILENS package will be released?

**Comment by dlee640** [comment]
@mcamurri the link you have attached is no longer available. Would you be kind to update the link? Thank you.

**Comment by mcamurri** [comment]
in a recent update, I've removed the symlink and copied the `iit/rbd` files inside the folder, here:
https://github.com/ori-drs/pronto/tree/master/pronto_quadruped_commons/include/iit/rbd
