### ISSUE TITLE
Run error about imu_link and simple_fusion/compressed/set_parameters

### ISSUE THREAD

**Issue by csufangyu** [ori-drs/pronto_anymal_example#14]
hi,I am trying to test it,but when i run it.I get the error as fellows:
```
process[fovis_trajectory_server-12]: started with pid [26044]
[ERROR] [1621906303.345119932]: "imu_link" passed to lookupTransform argument target_frame does not exist. 
```
and 

```
[ INFO] [1621906304.553449049]: /realsense_d435_front_forward/infra2/image_rect_raw is the image_b topic subscription [for stereo]
[ INFO] [1621906304.553710249]: compressed is the image_b_transport transport
[ERROR] [1621906304.558307283]: Tried to advertise a service that is already advertised in this node [/simple_fusion/compressed/set_parameters]
[ INFO] [1621906304.562073641]: StereoOdom Constructed
```
 I also try to change the CmakeLists.txt as https://github.com/ori-drs/pronto_anymal_example/issues/10#issuecomment-811024678

but it not use  for me.

![2021-05-25 09-36-56屏幕截图](https://user-images.githubusercontent.com/23466328/119427011-dc801100-bd3c-11eb-8678-04a065b0f9e2.png)

**Comment by wxmerkt** [comment]
Unclear to discern what the issue here is - if you can provide additional detail, please reopen the issue
