### ISSUE TITLE
Pronto Frame and Fovis Frame are strongly delayed

### ISSUE THREAD

**Issue by agutte** [ori-drs/pronto_anymal_example#15]
Hi, 

when I try to run your example as described, Pronto Frame and the Fovis Frame are strongly delayed: 
[](url)
![pronto_w_vo_normal](https://user-images.githubusercontent.com/38278267/121683354-8c83a700-cabd-11eb-8836-c9bd4da8b4f1.png)
On the screenshot, the  lowest frame is the Pronto Frame while the one closer to the robot is the Fovis Frame. 

However, when I play the rosbag file ten times slower (roslaunch option `--rate=0.1`), the delays disappear and the frames keep up with the robot as it is shown in the example screenshot of this repo. 
At first sight it seemed to me that maybe the computations of the VO node are too heavy for my system so I turned the Fovis node off in the  launch file. As a result the delay of the Pronto frame maybe slightly reduced, but is still outside of what I would expect (see screenshot below). 

![pronto_wo_VO_normal](https://user-images.githubusercontent.com/38278267/121684440-fbadcb00-cabe-11eb-8184-d770922c8d97.png)

In addition  to that, the console output delivers an error 
`[ERROR] [1623412330.431035104]: "base" passed to lookupTransform argument target_frame does not exist`
before the estimation starts. 
During  the state estimation, I continuously get the warning that the velocity could not be estimated: 

![Could_n_estimate](https://user-images.githubusercontent.com/38278267/121684866-90182d80-cabf-11eb-97d3-6568ca9e6258.png)

Is the delay of the estimation related to the error and warnings I get? And do you have any idea to solve this issue? 

I'm using Ubuntu 18.04 LTS with ROS Melodic

**Comment by wxmerkt** [comment]
My suspicion is that the project is not compiled in Release mode.

For the second warning - try reducing the force threshold.

**Comment by eshafeeqe** [comment]
Hi , 

I come across same issue. How to compile the project in release mode ?

**Comment by eshafeeqe** [comment]
Issue resolved. As @wxmerkt  suggested the package need to build in in release mode which can be enabled using the command below. 
```
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
```
