### ISSUE TITLE
Errors when buiding pronto_anymal_b

### ISSUE THREAD

**Issue by shuoli-robotics** [ori-drs/pronto_anymal_example#16]
Dear there,

I am trying to run the demo of pronto_anymal_example. I have cloned the required dependencies (fovis, fovis_ros and realsense2_description) to my catkin workspace. 

When I built the code by

`catkin build pronto_anymal_b` 

I received the error 

> Could not find a package configuration file provided by "eigen_utils"

So, I installed  "eigen_utils" from 

[http://wiki.ros.org/eigen_utils](url)

And then I built the package again by

`catkin build pronto_anymal_b`.

Then, I had the error message as 

> /home/shuo/catkin_ws/src/fovis_ros/fovis_ros/src/voconfig/voconfig.cpp:15:10: fatal error: eigen_utils/eigen_utils.hpp: No such file or directory
>    15 | #include <eigen_utils/eigen_utils.hpp>

I found that the eigen_utils package only has eigen_utils.h, so I tried to change the voconfig.cpp code to 

`#indclude eigen_utils.h`

but received the error 

> error: ‘getEulerAnglesDeg’ is not a member of ‘eigen_utils’
>    69 |             << eigen_utils::getEulerAnglesDeg(B_q_BC).transpose() << std::endl;

My pronto-fovis' branch is pronto-fovis and others' are master. I am using Ubuntu 20.04 and ROS Noetic.

Could you please give me a hint where I made mistakes?

Thanks in advance!
Shuo

**Comment by wxmerkt** [comment]
Hi Shuo,
You need eigen_utils from here: https://github.com/ori-drs/common_utils_drs

**Comment by shuoli-robotics** [comment]
Hi Wolfgang,

Thanks a lot! The problem was solved!

Cheers,
Shuo
