### ISSUE TITLE
issue with realsense, fovis

### ISSUE THREAD

**Issue by KyleM73** [ori-drs/pronto_anymal_example#2]
Hi, thanks for keeping this so well maintained!

2 issues:

1) In anymal_simple_b_description/urdf the realsense_d435i is called, but that isnt one of the sensors provided in realsense/realsense2_description/urdf. I was able to change the launch file anymal_simple_b_description/urdf/launch/load.launch to call _d435.urdf.xacro to resolve the issue though.

2) From the anymal example, the links for dependencies for both fovis and fovis_ros point to the same repository, and so when building the packages I get this, regardless of which branch I use:

$ catkin build

> Errors     << fovis_ros:cmake /home/kylem/Desktop/Pronto/logs/fovis_ros/build.cmake.008.log                                        
> CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
>   Could not find a package configuration file provided by "fovis" with any of
>   the following names:
> 
>     fovisConfig.cmake
>     fovis-config.cmake
> 
>   Add the installation prefix of "fovis" to CMAKE_PREFIX_PATH or set
>   "fovis_DIR" to a directory containing one of the above files.  If "fovis"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:6 (find_package)

It looks like its missing a separate package for fovis - is there a package build for this project? 

Thanks so much!

Ubunutu 18.04.5 (VM)
ROS Melodic
8 Gb RAM
70 Gb storage

**Comment by shivauchiha** [comment]
hi ! can you try cloning this repo:https://github.com/ori-drs/fovis into your catkin workspace and build ?

**Comment by mcamurri** [comment]
Dear @KyleM73,
thanks for your appreciation.

Yes, I've made a mistake in the README. The correct repository for fovis is the one pointed out by @shivauchiha . I will correct this in the README.

Regarding the realsense, the official repository from Intel did not have IMU included in their sensor description, so I had to make my own fork [here](https://github.com/ori-drs/realsense/tree/development-fixes) (also pointed in the README).

I assume you were using the official repository from Intel, hence the missing file.

Fortunately, they have recently accepted my PR so you can just update the official Intel repository, and you'll find the file.
