### ISSUE TITLE
RLException: unused args [simulation]

### ISSUE THREAD

**Issue by leyuan-sun** [ori-drs/pronto_anymal_example#3]
Starting  >>> anymal_b_simple_description                                                           
Starting  >>> eigen_utils                                                                           
Starting  >>> filter_tools                                                                          
Starting  >>> forward_kinematics                                                                    
Starting  >>> pronto_math                                                                           
Starting  >>> pronto_msgs                                                                           
Starting  >>> pronto_quadruped_commons                                                              
Starting  >>> stl_utils                                                                             
Finished  <<< anymal_b_simple_description                [ 0.1 seconds ]                            
Finished  <<< pronto_quadruped_commons                   [ 0.1 seconds ]                            
Finished  <<< filter_tools                               [ 0.2 seconds ]                            
Finished  <<< stl_utils                                  [ 0.2 seconds ]                            
Starting  >>> anymal_robcogen                                                                       
Finished  <<< eigen_utils                                [ 0.2 seconds ]                            
Starting  >>> eigen_utils_fftw                                                                      
Starting  >>> pronto_core                                                                           
Finished  <<< pronto_msgs                                [ 0.4 seconds ]                            
Finished  <<< forward_kinematics                         [ 0.2 seconds ]                            
Finished  <<< pronto_math                                [ 0.1 seconds ]                            
Finished  <<< anymal_robcogen                            [ 0.1 seconds ]                            
Starting  >>> pronto_anymal_commons                                                                 
Finished  <<< pronto_core                                [ 0.1 seconds ]                            
Starting  >>> pronto_biped_core                                                                     
Starting  >>> pronto_quadruped                                                                      
Starting  >>> pronto_ros                                                                            
Finished  <<< eigen_utils_fftw                           [ 0.1 seconds ]                            
Finished  <<< pronto_anymal_commons                      [ 0.1 seconds ]                            
Finished  <<< pronto_quadruped                           [ 0.1 seconds ]                            
Finished  <<< pronto_biped_core                          [ 0.2 seconds ]                            
Finished  <<< pronto_ros                                 [ 0.4 seconds ]                            
Starting  >>> pronto_biped_ros                                                                      
Starting  >>> pronto_quadruped_ros                                                                  
Finished  <<< pronto_quadruped_ros                       [ 0.4 seconds ]                            
Starting  >>> pronto_anymal                                                                         
Finished  <<< pronto_biped_ros                           [ 0.5 seconds ]                            
Finished  <<< pronto_anymal                              [ 0.1 seconds ]                            
[build] Summary: All 18 packages succeeded!                                                         
[build]   Ignored:   None.                                                                          
[build]   Warnings:  None.                                                                          
[build]   Abandoned: None.                                                                          
[build]   Failed:    None.                                                                          
[build] Runtime: 1.8 seconds total.                                                                 
sly@ubuntu:~/catkin_ws$ roslaunch pronto_anymal pronto_anymal.launch 
... logging to /home/sly/.ros/log/67769e4a-fbf6-11ea-af36-000c2916e9ad/roslaunch-ubuntu-48843.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: unused args [simulation] for include of [/home/sly/catkin_ws/src/anymal_b_simple_description/launch/load.launch]
The traceback for the exception was written to the log file
-------------------------------------------------------------------

When I run the  roslaunch pronto_anymal pronto_anymal.launch, the error shows as above, plz give me some instructions. Thanks ahead!

**Comment by mcamurri** [comment]
Dear @rginjapan, thanks for showing interest in my package. The error you are experiencing is probably originated from the following lines:
https://github.com/ori-drs/pronto_anymal_example/blob/01475843336b56f05f79258069f1f18b04a0f6c4/pronto_anymal/launch/pronto_anymal.launch#L17-L20

As you can see, I'm passing to `load.launch` an argument called `simulation`, which is defined here:
https://github.com/mcamurri/anymal_b_simple_description/blob/ec5a172276198c562df0d602f7e7a630cba75fa7/launch/load.launch#L4

My best guess is that you are using a wrong branch or fork of the `anymal_b_simple_description` package where the argument is not defined.

Can you check that you are using the right version of `anymal_b_simple_description`?

Hope that helps,
Marco.
